### ISSUE TITLE
Missing comma

### ISSUE THREAD

**Issue by sergey-serebryakov** [TalwalkarLab/paleo#1]
Hi! I think there is a missing comma in file "paleo/profilers/cudnn_profiler.py" at line 188 (after "3: 'CUDNN_CONVOLUTION_BWD_DATA_ALGO_FFT_TILING'"). Thanks!

**Comment by hang-qi** [comment]
@sergey-serebryakov Thanks for pointing out. I anticipate to add a linter and more tests soon.
